[package]
name = "Advent_of_Code"
version = "0.1.0"
authors = ["Logan SQUIREL <logan.squirel@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
