[package]
name = "aoc_2017_day_02"
version = "1.0.0"
authors = ["Logan SQUIREL <logan.squirel@protonmail.com>"]
edition = "2018"

[lib]
doctest = false

[[bin]]
name = "aoc_2017_day_02"
test = false

[dependencies]
